#requires -Version 7.0
# Feature: autofix-runtime-errors, Property 16: PowerShell 严格模式失败传播
#
# Pester 5 is required. If Get-Module -ListAvailable Pester reports < 5, run:
#     Install-Module Pester -MinimumVersion 5.0.0 -Force -SkipPublisherCheck
#
# Run with:
#     Invoke-Pester -Path Tests/AutoFix/strict-mode.Tests.ps1
#
# Validates Requirements 12.2 — design v2.0 §5.1 Property 16.
#
# NOTE: Per task 5.7, the test injects a deliberately failing command into a
# temp copy of each AutoFix script (originals never touched) and asserts the
# resulting copy exits non-zero. Because the AutoFix scripts dot-source
# _common.ps1 which sets `Set-StrictMode -Version Latest` and
# `$ErrorActionPreference = 'Stop'`, any uncaught native or terminating error
# must propagate.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

BeforeAll {
    $script:RepoRoot   = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..\..')).Path
    $script:ScriptsDir = Join-Path $script:RepoRoot 'scripts\autofix'
    if (-not (Test-Path -LiteralPath $script:ScriptsDir -PathType Container)) {
        throw "scripts/autofix not found at: $script:ScriptsDir"
    }

    $script:TmpRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("autofix-strict-" + [guid]::NewGuid().ToString('N').Substring(0, 8))
    New-Item -ItemType Directory -Path $script:TmpRoot -Force | Out-Null

    # Pool of failure injections. Each MUST trigger a non-zero exit under
    # StrictMode + ErrorActionPreference = Stop.
    $script:Injections = @(
        @{ Tag = 'undefined-var';    Code = 'Write-Output $ThisVariableDoesNotExist_8a2f' },
        @{ Tag = 'throw';            Code = 'throw "deliberate failure"' },
        @{ Tag = 'native-fail';      Code = '& cmd.exe /c "exit /b 7" ; if ($LASTEXITCODE -ne 0) { throw ("native failed: " + $LASTEXITCODE) }' },
        @{ Tag = 'cmdlet-error';     Code = 'Get-Content -LiteralPath (Join-Path $PSScriptRoot ("missing-" + [guid]::NewGuid().ToString("N") + ".dat"))' },
        @{ Tag = 'array-overrun';    Code = '$x = @(1,2,3); $null = $x[42]' },
        @{ Tag = 'divide-by-zero';   Code = '$null = 1 / 0' }
    )

    function script:Get-StrictScripts {
        $files = Get-ChildItem -LiteralPath $script:ScriptsDir -Filter '*.ps1' -File
        $list = New-Object System.Collections.Generic.List[string]
        foreach ($f in $files) {
            if ($f.Name -eq '_common.ps1') { continue }
            if ($f.Name.StartsWith('_'))   { continue }
            # Skip very large or interactive scripts that would exit nonzero
            # for unrelated reasons (e.g. require git/BDS wiring); the
            # injection probe targets the dot-source preamble, which is
            # identical for every script in the directory.
            $list.Add($f.FullName) | Out-Null
        }
        return ,@($list.ToArray())
    }

    function script:Build-InjectedCopy {
        <#
        .SYNOPSIS
            Produce a temp copy of $Source that runs only its strict-mode
            preamble (the . _common.ps1 dot-source) and then immediately
            executes a deliberately failing snippet. Original file is
            never modified.
        #>
        param([Parameter(Mandatory)][string]$Source, [Parameter(Mandatory)][string]$Tag, [Parameter(Mandatory)][string]$Code)
        $relName = [System.IO.Path]::GetFileNameWithoutExtension($Source)
        $stub = ('# Auto-generated by strict-mode.Tests.ps1' + [Environment]::NewLine + `
                 '# Source: {0}' + [Environment]::NewLine + `
                 '# Injection: {1}' + [Environment]::NewLine + `
                 '. "{2}\_common.ps1"' + [Environment]::NewLine + `
                 '{3}' + [Environment]::NewLine) -f $Source, $Tag, $script:ScriptsDir, $Code
        $dest = Join-Path $script:TmpRoot ('inj-' + $relName + '-' + $Tag + '-' + [guid]::NewGuid().ToString('N').Substring(0,6) + '.ps1')
        $enc  = [System.Text.UTF8Encoding]::new($false)
        [System.IO.File]::WriteAllText($dest, $stub, $enc)
        return $dest
    }

    function script:Run-Script {
        param([Parameter(Mandatory)][string]$Path)
        $null = & pwsh -NoProfile -NoLogo -NonInteractive -File $Path 2>$null
        return $LASTEXITCODE
    }
}

AfterAll {
    if ($script:TmpRoot -and (Test-Path -LiteralPath $script:TmpRoot)) {
        Remove-Item -LiteralPath $script:TmpRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Describe 'PowerShell strict mode — failure propagation' {

    Context 'Property 16: any failing command yields non-zero exit' {

        It 'propagates failures across 100 random script/injection combinations' {
            $iterations = 100
            $rng = [System.Random]::new(987654321)
            $scripts = Get-StrictScripts
            $scripts.Count | Should -BeGreaterThan 0
            $checked = 0
            for ($i = 0; $i -lt $iterations; $i++) {
                $src = $scripts[$rng.Next(0, $scripts.Count)]
                $inj = $script:Injections[$rng.Next(0, $script:Injections.Count)]
                $injected = Build-InjectedCopy -Source $src -Tag $inj.Tag -Code $inj.Code
                $rc = Run-Script -Path $injected
                $rc | Should -Not -Be 0
                $checked++
            }
            $checked | Should -Be $iterations
        }

        It 'a control script with no injection exits zero (sanity)' {
            $stub = ('. "{0}\_common.ps1"' + [Environment]::NewLine + `
                     'Write-Output "ok"' + [Environment]::NewLine) -f $script:ScriptsDir
            $dest = Join-Path $script:TmpRoot ('sanity-' + [guid]::NewGuid().ToString('N').Substring(0,6) + '.ps1')
            [System.IO.File]::WriteAllText($dest, $stub, [System.Text.UTF8Encoding]::new($false))
            (Run-Script -Path $dest) | Should -Be 0
        }
    }
}
