// AI-GENERATED
// DeepBase.Governance.AI.SteeringExporter.pas
// P13：AI-Steering 生成器 — 从治理模型导出 .kiro/steering/*.md

unit DeepBase.Governance.AI.SteeringExporter;

interface

uses
  System.SysUtils,
  System.Classes,
  System.IOUtils,
  System.Generics.Collections,
  DeepBase.Governance.Types,
  DeepBase.Governance.Model,
  DeepBase.Governance.KeyResolver,
  DeepBase.Governance.Purpose;

type
  TSteeringExporter = class
  private
    FKeyResolver: TKeyResolver;
    FPurposeSet: TPurposeSet;
    FOutputDir: string;
    function GenerateActionsSection: string;
    function GenerateGatesSection: string;
    function GeneratePurposesSection: string;
    function GenerateHeader: string;
  public
    constructor Create(AKeyResolver: TKeyResolver; APurposeSet: TPurposeSet;
      const AOutputDir: string);
    /// 导出完整 Steering 文件
    function Export: string;
    /// 导出到文件
    procedure ExportToFile(const AFileName: string = 'governance-model.md');
    /// 获取导出内容（不写文件）
    function GetContent: string;
    property OutputDir: string read FOutputDir write FOutputDir;
  end;

implementation

constructor TSteeringExporter.Create(AKeyResolver: TKeyResolver;
  APurposeSet: TPurposeSet; const AOutputDir: string);
begin
  inherited Create;
  FKeyResolver := AKeyResolver;
  FPurposeSet := APurposeSet;
  FOutputDir := AOutputDir;
end;

function TSteeringExporter.GenerateHeader: string;
begin
  Result :=
    '---' + #13#10 +
    'inclusion: auto' + #13#10 +
    '---' + #13#10 +
    '# OCGS Governance Model (Auto-Generated)' + #13#10 +
    #13#10 +
    '> This file is auto-generated by DeepBase.Governance.AI.SteeringExporter.' + #13#10 +
    '> Do not edit manually. Changes will be overwritten on next export.' + #13#10 +
    #13#10;
end;

function TSteeringExporter.GenerateActionsSection: string;
var
  LActions: TArray<TAction>;
  LA: TAction;
begin
  Result := '## Actions' + #13#10 + #13#10;
  Result := Result + '| Key | Name | Risk | Gate | Purpose |' + #13#10;
  Result := Result + '|-----|------|------|------|---------|' + #13#10;

  LActions := FKeyResolver.GetAllActions;
  for LA in LActions do
  begin
    Result := Result + '| ' + LA.Key +
      ' | ' + LA.DisplayName +
      ' | ' + IntToStr(Ord(LA.RiskLevel)) +
      ' | ' + LA.GateKey +
      ' | ' + LA.PurposeKey +
      ' |' + #13#10;
  end;
  Result := Result + #13#10;
end;

function TSteeringExporter.GenerateGatesSection: string;
var
  LGates: TArray<TAccessGate>;
  LG: TAccessGate;
begin
  Result := '## Gates' + #13#10 + #13#10;
  Result := Result + '| Key | Name | Type | Actions |' + #13#10;
  Result := Result + '|-----|------|------|---------|' + #13#10;

  LGates := FKeyResolver.GetAllGates;
  for LG in LGates do
  begin
    Result := Result + '| ' + LG.Key +
      ' | ' + LG.DisplayName +
      ' | ' + IntToStr(Ord(LG.GateType)) +
      ' | ' + String.Join(', ', LG.ActionKeys.ToArray) +
      ' |' + #13#10;
  end;
  Result := Result + #13#10;
end;

function TSteeringExporter.GeneratePurposesSection: string;
var
  LPurposes: TArray<TPurpose>;
  LP: TPurpose;
begin
  Result := '## Purposes' + #13#10 + #13#10;
  Result := Result + '| Key | Name | Parent | Status |' + #13#10;
  Result := Result + '|-----|------|--------|--------|' + #13#10;

  if FPurposeSet <> nil then
  begin
    LPurposes := FPurposeSet.GetAll;
    for LP in LPurposes do
    begin
      Result := Result + '| ' + LP.Key +
        ' | ' + LP.Name +
        ' | ' + LP.ParentKey +
        ' | ' + LP.Status +
        ' |' + #13#10;
    end;
  end;
  Result := Result + #13#10;
end;

function TSteeringExporter.Export: string;
begin
  Result := GetContent;
  ExportToFile;
end;

function TSteeringExporter.GetContent: string;
begin
  Result := GenerateHeader +
    GeneratePurposesSection +
    GenerateGatesSection +
    GenerateActionsSection;
end;

procedure TSteeringExporter.ExportToFile(const AFileName: string);
var
  LPath: string;
  LContent: string;
begin
  LContent := GetContent;
  if FOutputDir <> '' then
  begin
    if not TDirectory.Exists(FOutputDir) then
      TDirectory.CreateDirectory(FOutputDir);
    LPath := TPath.Combine(FOutputDir, AFileName);
    TFile.WriteAllText(LPath, LContent, TEncoding.UTF8);
  end;
end;

end.
